#!/usr/bin/python3
import argparse
import inspect
import cmd
import sys
import os


try:
    import PyWordReference
except Exception as e:
    module_path = os.path.join(
                      os.path.dirname(
                         os.path.abspath(inspect.getsourcefile(lambda:0))),
                                         "PyWordReference-submodule")
    sys.path.append(module_path)
    import PyWordReference


class DictionaryShell(cmd.Cmd):
    intro = 'Welcome to the turtle shell.   Type help or ? to list commands.\n'
    prompt = '(dictionary) '
    file = None

    def __find_wr_trans(self, _from, _to, arg):
        """Run Transation using Wordreference"""
        try:
            w = PyWordReference.Translator(self.wr_api_key)
            res = w.search(_from, _to, arg)
            print("Copyright WordReference: {url}".format(url=res["url"]))
            for t in res["translation"]:
                print(str(t).encode('ascii', 'ignore').decode("ascii"))
            print("")
        except PyWordReference.TranslatorException as e:
            print(e)

    def find_wr_enit(self, arg):
        """Find function from English to Italian using Wordreference"""
        self.__find_wr_trans("en", "it", arg)

    def find_wr_iten(self, arg):
        """Find function from Italian to English using Wordreference"""
        self.__find_wr_trans("it", "en", arg)

    dictionaries = {
        "wr-enit" : {
            "name": "wr-enit",
            "description": "Translate English to Italian using WordReference",
            "find": find_wr_enit,
        },
        "wr-iten" : {
            "name": "wr-iten",
            "description": "Translate Italian to English using WordReference",
            "find": find_wr_iten,
        },
    }

    def __init__(self, wr_api_key=None):
        self.current_dictionary = "N/A"
        self.wr_api_key = wr_api_key
        super(DictionaryShell, self).__init__()
        self.do_help("")
        self.intro = """
This is a command line tools to access online dictionaries.

Read the command help message for more information about how to use the command.
"""

    def do_quit(self, arg):
        """
        quit: exit from this program
        """
        return True

    do_EOF = do_quit

    def do_list(self, arg):
        """
        list: list all available dictionaries

            list

        The output format is 'name: description'.
        It will highlight the dictionary in use (if any)
        """
        for d in self.dictionaries:
            if d == self.current_dictionary:
                print("[{name}]: {description}".format(**self.dictionaries[d]))
            else:
                print("{name}: {description}".format(**self.dictionaries[d]))
        print("")

    def do_select(self, arg):
        """
        select: select the dictionary to use

           select <dictionary-name>

        You can use the ``list`` command for the list of available dictionaries
        """

        if arg in self.dictionaries:
            self.current_dictionary = arg
        else:
            print("Dictionary \"{}\" does not exist".format(arg))

    def do_find(self, arg):
        """
        find: find a word in the current dictionary
        """
        if " " in arg:
            print("For the time being this program support only single words")
            return False
        self.dictionaries[self.current_dictionary]["find"](self, arg)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--wr-api-key', dest='api_key', default=None,
                    help='WordReference API key')
    args = parser.parse_args()

    if args.api_key is None and 'WR_API_KEY' in os.environ:
        args.api_key = os.environ['WR_API_KEY']

    DictionaryShell(wr_api_key=args.api_key).cmdloop()
